export const ADD_NEW_MEETUP = "ADD_NEW_MEETUP";
export const ADD_INITIAL_MEETUP_LIST = "ADD_INITIAL_MEETUP_LIST";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
